version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file: .env
    expose:
      - 9000
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - app

networks:
  app:
    external: true
