version: '3'

services:
  postgres:
    image: docker.io/library/postgres:alpine
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 80s
    networks:
      - app

networks:
  app:
    external: true
