version: '3'

services:
  redis:
    image: docker.io/library/redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - app

networks:
  app:
    external: true
